services:
  - type: web
    name: pofolio
    env: node
    plan: free
    branch: main
    # Build script will build the frontend and install server deps
    buildCommand: "bash ./render-build.sh"
  startCommand: "node index.cjs"
    # Root stays at repo root; render-build.sh will handle building the frontend into ./dist
    envVars:
      - key: PORT
        value: "4000"
      - key: SMTP_HOST
        fromDatabase: false
      - key: SMTP_PORT
        fromDatabase: false
      - key: SMTP_SECURE
        fromDatabase: false
      - key: SMTP_USER
        fromDatabase: false
      - key: SMTP_PASS
        fromDatabase: false
      - key: SMTP_FROM
        fromDatabase: false
      - key: CONTACT_RECEIVER
        fromDatabase: false

# Note: set the SMTP_* env vars in the Render dashboard for the service securely.
